language: python

os:
- linux

python:
- "3.6"

before install:
- sudo apt install python3-rtree
- pip3 install Cython
- bash install-proto.sh

install:
- python3 setup.py install

script:
- pytest

addons:
  homebrew:
    packages:
      spatialindex