
language: python

os:
- linux

python:
- "3.6"

before install:
- sudo apt-get update
- sudo apt-get install libspatialindex-dev

install:
- bash install-proto.sh
- pip3 install .

script:
- pytest tests/