
language: python

os:
- linux

include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

python:
- "3.6"

before install:
- sudo apt-get update
- sudo apt-get install libspatialindex-dev

install:
- pip3 install cython
- cython --cplus spatial_access/*.pyx
- pip3 install .

script:
- pytest tests/