language: python

os:
- linux

python:
- "3.6"

before install:
- sudo apt-get install libprotobuf-dev protobuf-compiler
- pip3 install Cython

install:
- pip3 install pylint
- pip3 install . 

script:
- pytest
