
language: python

os:
- linux

dist: xenial

compiler: clang

python:
- "3.6"

before install:
- sudo apt-get update
- sudo apt-get install libspatialindex-dev

install:
- pip3 install cython
- pip3 install osmnet
- cython --cplus spatial_access/*.pyx
- python3 setup.py sdist build_ext
- python3 setup.py install

script:
- pytest tests/