
language: python

os:
- linux

python:
- "3.6"

before install:
- sudo apt-get update
- sudo apt-get install libspatialindex-dev

install:
- pip3 install cython
- cython --cplus spatial_access/*.pyx
- sudo pip3 install dist/spatial_access-*.tar.gz

script:
- pytest tests/