language: python

os:
- linux

python:
- "3.6"

before install:
- sudo apt install python3-rtree
- pip3 install Cython

install:
- pip3 install pylint
- python3 setup.py install

script:
- pytest

addons:
  homebrew:
    packages:
      spatialindex