language: pythonq

os:
- linux

python:
- "3.6"

before install:
- sudo apt install python3-rtree
- pip3 install Cython
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install gcc-7.3 -y

install:
- CC=gcc-7.3 CXX=g++7.3
- bash install-proto.sh
- pip3 install .

script:
- pytest tests/

addons:
  homebrew:
    packages:
      spatialindex