
language: python

os:
- linux

include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

python:
- "3.6"

before install:
- sudo apt-get update
- sudo apt-get install libspatialindex-dev

install:
- pip3 install cython
- cython --cplus spatial_access/*.pyx
- pip3 install dist/spatial_access-*.tar.gz

script:
- pytest tests/